services:
  web:
    image: node:14
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run start"
    environment:
      - NODE_ENV=development
